site_name: younginger 的摸鱼手册
theme:
  name: material
  features:
    - navigation.tabs # 开启顶部导航栏
    - content.code.copy # 代码块右上角显示“复制”按钮

# 必要的插件和扩展
markdown_extensions:
  - admonition #以此开启提示框功能
  - pymdownx.highlight: # 代码高亮
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex: # 开启数学公式支持
      generic: true

# 加载 MathJax (渲染数学公式的引擎)
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js